---

- name: Install nginx
  apt:
    name: nginx
    update_cache: yes
  become: yes

- name: Install and refresh snap
  command: {{ item }}
  with_items:
    - 'snap install core'
    - 'snap refresh core'
  become: yes

- name: Install certbot
  snap:
    name: certbot
    classic: yes
  become: yes

- name: Adding certbot symlink
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    owner: root
    group: root
    state: link
    mode: '0755'
  become: yes

-name: Run certbot
  command: certbot -n --nginx certonly --domains vv.wangdongustc.com
  
    
