---

- name: Install trojan from apt
  apt:
    name: trojan
    update_cache: yes

- name: Config trojan as client
  template:
    src: templates/config.json.j2
    dest: /etc/trojan/config.json

- name: Enable the trojan service
  systemd:
    name: trojan
    enabled: yes
    daemon_reload: yes
    state: restarted
